DocumentSystemApp/Controllers/ChangeRequestFormsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DocumentSystemApp.Data;
using DocumentSystemApp.Data.Entities;
using Microsoft.AspNetCore.Identity;
using DocumentSystemApp.Models;
using DocumentSystemApp.Models.ChangeRequestFormViewModels;
using DocumentSystemApp.Repositories;
using AutoMapper;

namespace DocumentSystemApp.Controllers
{
    public class ChangeRequestFormsController : Controller
    {
        private readonly DocumentSystemDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IChangeRequestFormRepository _changeRequestFormRepository;
        private readonly IMapper _mapper;

        public ChangeRequestFormsController(DocumentSystemDbContext context, 
            UserManager<ApplicationUser> userManager,
            IChangeRequestFormRepository changeRequestFormRepository,
            IMapper mapper)
        {
            _context = context;
            _userManager = userManager;
            _changeRequestFormRepository = changeRequestFormRepository;
            _mapper = mapper;
        }

        // GET: ChangeRequestForms
        public async Task<IActionResult> Index()
        {
            var model = _changeRequestFormRepository.ChangeRequestFormLists();
            return View(model);
        }

        // GET: ChangeRequestForms/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var changeRequestForm = _changeRequestFormRepository.GetById(id.Value);
            
            //var changeRequestForm = await _context.ChangeRequestForms
            //    .SingleOrDefaultAsync(m => m.ChangeRequestFormId == id);
            if (changeRequestForm == null)
            {
                return NotFound();
            }
            var model = _mapper.Map<ChangeRequestForm, RequestFormCreateEditViewModel>(changeRequestForm);

            return View(model);
        }

        // GET: ChangeRequestForms/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: ChangeRequestForms/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(RequestFormCreateEditViewModel requestFormCreateEditViewModel)
        {
            if (requestFormCreateEditViewModel.ChangeRequestFormId != null)
            {
                requestFormCreateEditViewModel.ChangeRequestFormId = null;
            }

            if (ModelState.IsValid)
            {
                var userID = _userManager.GetUserId(User);
                var model = _mapper.Map<RequestFormCreateEditViewModel, ChangeRequestForm>(requestFormCreateEditViewModel);
                model.CreateDate = DateTime.Now;
                model.CreatorUserId = userID;
                _changeRequestFormRepository.Create(model);
                return RedirectToAction(nameof(Index));
            }
            return View(requestFormCreateEditViewModel);
        }

        // GET: ChangeRequestForms/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var changeRequestForm = _changeRequestFormRepository.GetById(id.Value);

            if (changeRequestForm == null)
            {
                return NotFound();
            }
            var model = _mapper.Map<ChangeRequestForm, RequestFormCreateEditViewModel>(changeRequestForm);

            //var changeRequestForm = await _context.ChangeRequestForms.SingleOrDefaultAsync(m => m.ChangeRequestFormId == id);
            //if (changeRequestForm == null)
            //{
            //    return NotFound();
            //}
            return View(model);
        }

        // POST: ChangeRequestForms/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(RequestFormCreateEditViewModel requestFormCreateEditViewModel)
        {
            if (requestFormCreateEditViewModel.ChangeRequestFormId == null || requestFormCreateEditViewModel.ChangeRequestFormId == 0)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var userID = _userManager.GetUserId(User);
                    var model = _mapper.Map<RequestFormCreateEditViewModel, ChangeRequestForm>(requestFormCreateEditViewModel);
                    model.CreateDate = DateTime.Now;
                    model.CreatorUserId = userID;
                    _changeRequestFormRepository.Update(model);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ChangeRequestFormExists(requestFormCreateEditViewModel.ChangeRequestFormId.Value))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(requestFormCreateEditViewModel);
        }

        // GET: ChangeRequestForms/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var changeRequestForm = await _context.ChangeRequestForms
                .SingleOrDefaultAsync(m => m.ChangeRequestFormId == id);
            if (changeRequestForm == null)
            {
                return NotFound();
            }

            return View(changeRequestForm);
        }

        // POST: ChangeRequestForms/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var changeRequestForm = await _context.ChangeRequestForms.SingleOrDefaultAsync(m => m.ChangeRequestFormId == id);
            _context.ChangeRequestForms.Remove(changeRequestForm);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ChangeRequestFormExists(int id)
        {
            return _context.ChangeRequestForms.Any(e => e.ChangeRequestFormId == id);
        }
    }
}

DocumentSystemApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DocumentSystemApp</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar fixed-top navbar-expand-md navbar-dark bg-dark">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a asp-area="" asp-controller="Home" asp-action="Index" class="nav-link">Home</a>
                </li>
                <li class="nav-item">
                    <a asp-area="" asp-controller="Home" asp-action="About" class="nav-link">About</a>
                </li>
                <li class="nav-item">
                    <a asp-area="" asp-controller="Home" asp-action="Contact" class="nav-link">Contact</a>
                </li>
                <li class="nav-item">
                    <a asp-area="" asp-controller="ChangeRequestForms" asp-action="Index" class="nav-link">Change Request Forms</a>
                </li>
            </ul>
            @await Html.PartialAsync("_LoginPartial")
            @*<form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>*@
        </div>
    </nav>


    @*<nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">DocumentSystemApp</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                    <li><a asp-area="" asp-controller="ChangeRequestForms" asp-action="Index">Change Request Forms</a></li>
                </ul>
               
            </div>
        </div>
    </nav>*@
    <br />
    <br />
    <br />
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - DocumentSystemApp</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN">
        </script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>